name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel setuptools Cython

      - name: Build package in development mode
        run: |
          python -m pip install -e .

      - name: Install test dependencies
        run: |
          python -m pip install ".[test]"

      - name: Run tests with pytest
        run: |
          python -m pytest tests/ -v --cov=hyperq --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  build-linux-wheels:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/hyperq

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Linux wheels
        uses: pypa/cibuildwheel@v2.16.2

      - name: Upload Linux wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheels
          path: wheelhouse/
          retention-days: 1

  build-macos-wheels:
    runs-on: macos-latest
    needs: test
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/hyperq

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build macOS wheels
        uses: pypa/cibuildwheel@v2.16.2

      - name: Upload macOS wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels
          path: wheelhouse/
          retention-days: 1

  build-sdist:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/hyperq

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel setuptools Cython

      - name: Build source distribution
        run: |
          python -m build --sdist

      - name: Upload source distribution as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/
          retention-days: 1

  upload-to-pypi:
    runs-on: ubuntu-latest
    needs: [build-linux-wheels, build-macos-wheels, build-sdist]
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/hyperq

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Combine all packages
        run: |
          mkdir -p combined-packages
          # Copy Linux wheels
          if [ -d "artifacts/linux-wheels" ]; then
            cp artifacts/linux-wheels/* combined-packages/
          fi
          # Copy macOS wheels
          if [ -d "artifacts/macos-wheels" ]; then
            cp artifacts/macos-wheels/* combined-packages/
          fi
          # Copy source distribution
          if [ -d "artifacts/sdist" ]; then
            cp artifacts/sdist/* combined-packages/
          fi
          ls -la combined-packages/

      - name: Upload all packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: combined-packages/
          skip-existing: true
